# Releases the application to different environments based on the branch it is running on
name: Release to Dev

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'env/helm/**'
      - 'env/terraform/**'
      - '!env/terraform/shared/**'

concurrency:
  group: release-dev
  cancel-in-progress: false

env:
  VERSION: 1.0.${{ github.run_id }}-dev

jobs:
  build:
    name: Build Container Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Container images
        uses: ./.github/actions/containers
        with:
          container-registry-server: ${{ secrets.CONTAINER_REGISTRY_SERVER }}
          container-registry-username: ${{ secrets.AZURE_APP_ID }}
          container-registry-password: ${{ secrets.AZURE_PASSWORD }}
          wemogy-packages-token: ${{ secrets.WEMOGY_PACKAGES_TOKEN }}
          version: ${{ env.VERSION }}
          push: true

  dev:
    name: Deploy to Development
    environment:
      name: Development
      url: https://dev.<%= envUrl %>
    needs: build
    runs-on: ubuntu-latest
    concurrency: terraform
    steps:
      - uses: actions/checkout@v2

      - name: Terraform Infrastructure
        uses: wemogy/terraform-action@1.4.0
        id: terraform
        with:
          apply: true
          working-directory: env/terraform/individual
          client-id: ${{ secrets.AZURE_APP_ID }}
          client-secret: ${{ secrets.AZURE_PASSWORD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          backend-storage-account-name: <%= name %>tfstate
          backend-container-name: tfstate-dev
          backend-key: dev.tfstate
          backend-access-key: ${{ secrets.TERRAFORM_BACKEND_ACCESS_KEY }}
        env:
          TF_VAR_environment: dev
          TF_VAR_azure_aks_name: ${{ secrets.AKS_NAME }}
          TF_VAR_azure_aks_resource_group: ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Deploy Helm Chart
        uses: ./.github/actions/helm-deploy
        with:
          client-id: ${{ secrets.AZURE_APP_ID }}
          client-secret: ${{ secrets.AZURE_PASSWORD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          name: <%= name %>-dev
          version: ${{ env.VERSION }}
          domain-prefix: dev
          terraform-output: ${{ steps.terraform.outputs.output }}
          namespace: <%= name %>-dev
          aks-name: ${{ secrets.AKS_NAME }}
          aks-resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          container-registry-server: ${{ secrets.CONTAINER_REGISTRY_SERVER }}
          wemogy-pull-secret-username: ${{ secrets.WEMOGY_PULL_SECRET_USERNAME }}
          wemogy-pull-secret-password: ${{ secrets.WEMOGY_PULL_SECRET_PASSWORD }}
