name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  containers:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
<% if(dotnet) { %>
      - name: Build .NET
        uses: <%= buildDotnetActionPath %>
        with:
          wemogy-packages-token: ${{ secrets.WEMOGY_PACKAGES_TOKEN }}
          version: 0.0.0-test
<% } if(javaScript) { %>
      - name: Build JavaScript
        uses: <%= buildJavaScriptActionPath %>
        with:
          wemogy-packages-token: ${{ secrets.WEMOGY_PACKAGES_TOKEN }}
          version: 0.0.0-test
<% } if(containers) { %>
      - name: Build Containers
        uses: <%= containersActionPath %>
        with:
          container-registry-server: test
          wemogy-packages-token: ${{ secrets.WEMOGY_PACKAGES_TOKEN }}
          version: 0.0.0-test
          push: false
<% } %>
