apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-<%= name %>
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: env/dapr/secrets/secrets.json
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <%= name %>
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: <%= keyVaultName %>
    - name: azureTenantId
      secretKeyRef:
        name: LocalDevServicePrincipalTenantId
        key: LocalDevServicePrincipalTenantId
    - name: azureClientId
      secretKeyRef:
        name: LocalDevServicePrincipalAppId
        key: LocalDevServicePrincipalAppId
    - name: azureClientSecret
      secretKeyRef:
        name: LocalDevServicePrincipalPassword
        key: LocalDevServicePrincipalPassword
auth:
  secretStore: local-secret-store
