apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-<%= service %>
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-<%= service %>
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-<%= service %>
      {{- if .Values.<%= service %>.podLabels }}
        {{- toYaml .Values.<%= service %>.podLabels | nindent 8 }}
      {{- end }}
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: '<%= service %>'
        dapr.io/app-port: '80'
    spec:
      containers:
      - name: <%= service %>
        image: {{ .Values.<%= service %>.image.repository }}:{{ tpl .Values.<%= service %>.image.tag . }}
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"
