apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    cert-manager.io/issuer: {{ .Release.Name }}-letsencrypt-{{ .Values.ingress.tls.letsencrypt.environment }}

spec:
  tls:
    - secretName: {{ .Release.Name }}-tls
      hosts:
        - {{ include "<%= service %>Url" . }}

  rules:
    - host: {{ include "<%= service %>Url" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-<%= service %>
                port:
                  name: http
