apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: {{ .Values.settings.azure.keyVault.name }}
