apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wemogy-<%= name %>-<%= service %>
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wemogy-<%= name %>-<%= service %>
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wemogy-<%= name %>-<%= service %>
      {{- if .Values.<%= service %>.podLabels }}
        {{- toYaml .Values.<%= service %>.podLabels | nindent 8 }}
      {{- end }}
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: '<%= service %>'
        dapr.io/app-port: '80'
    spec:
      serviceAccountName: {{ .Release.Name }}-wemogy-<%= name %>
      containers:
      - name: app
        image: {{ .Valuesy.<%= service %>.repository }}:{{ tpl .Values.<%= service %>.tag . }}
        env:
        - name: CONFIG_PATH
          value: /etc/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: {{ tpl .Values.images.wemogy.pullSecret.name . }}
      volumes:
      - name: config
        configMap:
          {{- if .Values.config.content  }}
          name: {{ .Release.Name }}-<%= name %>-config
          {{- end }}
          {{- if .Values.config.configMap.name  }}
          name: {{.Values.config.configMap.name  }}
          {{- end }}
