{{- if .Values.images.wemogy.pullSecret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wemogy-<%= name %>-pull-secret
data:
  .dockerconfigjson: {{ include "wemogy<%= name.pascalCase %>DockerLoginPullSecretContent" . | b64enc }}
type: kubernetes.io/dockerconfigjson
{{- end }}
