apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-wemogy-<%= name %>
---
{{- if .Values.enableRbac  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-wemogy-<%= name %>
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-wemogy-<%= name %>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-wemogy-<%= name %>
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-wemogy-<%= name %>
{{- end }}
