apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wemogy-<%= name %>-secrets
type: Opaque
data:
  MyServiceConnectionString: {{ .Values.settings.demo.myService.connectionString | b64enc }} # TODO: Change to real value
