name: Deploy Pull Request

on:
  pull_request:
    paths:
      - 'src/**'
      - 'env/**'
    types:
      - opened
      - reopened
      - labeled
      - synchronize

env:
  VERSION: 1.0.${{ github.run_id }}
  SLUG: pr${{ github.event.pull_request.number }}

jobs:
  setup:
    name: Setup
    # If this workflow gets executed by labeling a PR, the label must contain 'deploy' to execute this job
    # As all other jobs depend on 'setup', we only need to ckeck this once here
    if: github.event.label.name == '' || contains(github.event.label.name, 'deploy')
    runs-on: ubuntu-latest
    outputs:
      is-deployment-needed: ${{ steps.get-environment.outputs.is-deployment-needed }}
      is-custom-environment: ${{ steps.get-environment.outputs.is-custom-environment }}
      env: ${{ steps.get-environment.outputs.env }}
    steps:
      - uses: actions/checkout@v2

      - name: Get Environment
        id: get-environment
        uses: wemogy/get-environment-action@v2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-pr:
    if: needs.setup.outputs.is-deployment-needed == 'true'
    name: Deploy to PR Environment
    runs-on: ubuntu-latest
    needs: setup
    concurrency: terraform
    outputs:
      terraform-stage-output: ${{ steps.terraform-stage.outputs.output }}
    steps:
      - uses: actions/checkout@v2

      - name: Build and Push Container images
        uses: ./.github/actions/containers
        with:
          container-registry-server: ${{ secrets.CONTAINER_REGISTRY_SERVER }}
          container-registry-username: ${{ secrets.AZURE_APP_ID }}
          container-registry-password: ${{ secrets.AZURE_PASSWORD }}
          wemogy-packages-token: ${{ secrets.WEMOGY_PACKAGES_TOKEN }}
          version: ${{ env.VERSION }}
          push: true

      - name: Terraform Infrastructure
        uses: wemogy/terraform-action@1.4.0
        id: terraform
        with:
          apply: true
          working-directory: env/terraform/stage
          client-id: ${{ secrets.AZURE_APP_ID }}
          client-secret: ${{ secrets.AZURE_PASSWORD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          backend-storage-account-name: digittooltfstate
          backend-container-name: tfstate
          backend-key: ${{ needs.setup.outputs.env }}.tfstate
          backend-access-key: ${{ secrets.TERRAFORM_BACKEND_ACCESS_KEY }}
        env:
          TF_VAR_environment: ${{ needs.setup.outputs.env }}
          TF_VAR_azure_aks_name: ${{ secrets.AKS_NAME }}
          TF_VAR_azure_aks_resource_group: ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Deploy Helm Chart
        uses: ./.github/workflows/helm-deploy
        with:
          client-id: ${{ secrets.AZURE_APP_ID }}
          client-secret: ${{ secrets.AZURE_PASSWORD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          name: digittool-${{ env.SLUG }}
          version: ${{ env.VERSION }}
          domain-prefix: env.SLUG
          terraform-output: ${{ steps.terraform.outputs.output }}
          namespace: digittool-${{ env.SLUG }}
          aks-name: ${{ secrets.AKS_NAME }}
          aks-resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          container-registry-server: ${{ secrets.CONTAINER_REGISTRY_SERVER }}
          wemogy-pull-secret-username: ${{ secrets.WEMOGY_PULL_SECRET_USERNAME }}
          wemogy-pull-secret-password: ${{ secrets.WEMOGY_PULL_SECRET_PASSWORD }}

      - name: Post comment to Pull Request
        if: needs.setup.outputs.is-pull-request == 'true'
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Your Pull Request Deployment is ready for review at https://app.pr.my-app.de"
          check_for_duplicate_msg: true
