apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-<%= name %>
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: env/dapr/secrets/secrets.json
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <%= name %>
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: <%= keyVaultName %>
    - name: azureTenantId
      secretKeyRef:
        name: DevAppServicePrincipalTenantId
        key: DevAppServicePrincipalTenantId
    - name: azureClientId
      secretKeyRef:
        name: DevAppId
        key: DevAppId
    - name: azureClientSecret
      secretKeyRef:
        name: DevAppServicePrincipalPassword
        key: DevAppServicePrincipalPassword
auth:
  secretStore: local-secret-store
