name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  javascript:
    name: Build JavaScript
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install packages
        run: yarn install
      - name: Build application
        run: yarn build
